### ISSUE TITLE
支持i686-pc-windows-msvc

### ISSUE THREAD

**Issue by gqf2008** [hamflx/forward-dll#2]
@hamflx 很好的工具库，请支持下i686-pc-windows-msvc目标架构，谢谢。

**Comment by hamflx** [comment]
@gqf2008 已发新版本（v0.1.14）支持 32 位，使用方法如下：

```rust
use forward_dll::forward_dll;

fn main() {
  // 32 位目标。
  forward_dll("C:\\Windows\\SysWOW64\\version.dll").unwrap();
}
```

但是构建产物仅支持 64 位系统下的 32 位模式（硬编码了 SysWOW64/version.dll）。

**Comment by hamflx** [comment]
@gqf2008 上面说的不对，32 位程序也可以直接写 `forward_dll("C:\\Windows\\system32\\version.dll").unwrap();`，测试下是能用的，可能是 Windows 自动转到 SysWOW64 目录里面去了。这样对于 32 位系统应该也能兼容了。

**Comment by gqf2008** [comment]
@hamflx 好的，辛苦了，我测试下。

**Comment by gqf2008** [comment]
@hamflx 不行
[build]
target = "i686-pc-windows-msvc"

错误如下，可能是寄存器名称不对吧，32位应该是E开头的
error: register %rcx is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:2:7
  |
2 |     push rcx
  |          ^^^

error: register %rdx is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:3:6
  |
3 | push rdx
  |      ^^^

error: register %r8 is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:4:6
  |
4 | push r8
  |      ^^

error: register %r9 is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:5:6
  |
5 | push r9
  |      ^^

error: register %r10 is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:6:6
  |
6 | push r10
  |      ^^^

error: register %r11 is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:7:6
  |
7 | push r11
  |      ^^^

error: register %rsp is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:2:6
  |
2 |     sub rsp, 28h
  |         ^^^

error: register %rax is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:3:6
  |
3 | call rax
  |      ^^^

error: register %rsp is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:4:5
  |
4 | add rsp, 28h
  |     ^^^

error: register %r11 is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:2:6
  |
2 |     pop r11
  |         ^^^

error: register %r10 is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:3:5
  |
3 | pop r10
  |     ^^^

error: register %r9 is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:4:5
  |
4 | pop r9
  |     ^^

error: register %r8 is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:5:5
  |
5 | pop r8
  |     ^^

error: register %rdx is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:6:5
  |
6 | pop rdx
  |     ^^^

error: register %rcx is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:7:5
  |
7 | pop rcx
  |     ^^^

error: register %rax is only available in 64-bit mode
  |
note: instantiated into assembly here
 --> <inline asm>:8:5
  |
8 | jmp rax

**Comment by gqf2008** [comment]
静态的可以编译通过，可以加载dll，但是函数转发应该没有正确，我的测试例子没有跑起来，下面是我的手写跳转，32位程序可以跑起来

std::arch::asm!(
        "jmp eax",
        in("eax") RealVerQueryValueW,
        options(nostack)
    );

**Comment by hamflx** [comment]
@gqf2008 你没有给例子，我以为是静态的，所以支持的是静态的。动态的我有空看下。

**Comment by hamflx** [comment]
@gqf2008 可以细说下，静态转发的具体问题。

**Comment by hamflx** [comment]
@gqf2008 动态转发应该也可以了，可以试一下 v0.1.15。

**Comment by gqf2008** [comment]
@hamflx 
1、动态转发、动态自定义转发都可以了，最好把DllMain给隐藏掉，通过自定义导出表可以实现（/DEF:exports.def）
2、静态转发还是不行，导出表如下
Ordinal 	Rva     	Function Name             	区段    	Entry Point(中转输出表)                                    	
00000001	0002CF4C	GetFileVersionInfoA       	.rdata	C:\Windows\SysWOW64\version.GetFileVersionInfoA       	
00000002	0002CF97	GetFileVersionInfoByHandle	.rdata	C:\Windows\SysWOW64\version.GetFileVersionInfoByHandle	
00000003	0002CFE4	GetFileVersionInfoExA     	.rdata	C:\Windows\SysWOW64\version.GetFileVersionInfoExA     	
00000004	0002D02C	GetFileVersionInfoExW     	.rdata	C:\Windows\SysWOW64\version.GetFileVersionInfoExW     	
00000005	0002D076	GetFileVersionInfoSizeA   	.rdata	C:\Windows\SysWOW64\version.GetFileVersionInfoSizeA   	
00000006	0002D0C4	GetFileVersionInfoSizeExA 	.rdata	C:\Windows\SysWOW64\version.GetFileVersionInfoSizeExA 	
00000007	0002D114	GetFileVersionInfoSizeExW 	.rdata	C:\Windows\SysWOW64\version.GetFileVersionInfoSizeExW 	
00000008	0002D162	GetFileVersionInfoSizeW   	.rdata	C:\Windows\SysWOW64\version.GetFileVersionInfoSizeW   	
00000009	0002D1AA	GetFileVersionInfoW       	.rdata	C:\Windows\SysWOW64\version.GetFileVersionInfoW       	
0000000A	0002D1E7	VerFindFileA              	.rdata	C:\Windows\SysWOW64\version.VerFindFileA              	
0000000B	0002D21D	VerFindFileW              	.rdata	C:\Windows\SysWOW64\version.VerFindFileW              	
0000000C	0002D256	VerInstallFileA           	.rdata	C:\Windows\SysWOW64\version.VerInstallFileA           	
0000000D	0002D292	VerInstallFileW           	.rdata	C:\Windows\SysWOW64\version.VerInstallFileW           	
0000000E	0002D2CF	VerLanguageNameA          	.rdata	C:\Windows\SysWOW64\version.VerLanguageNameA          	
0000000F	0002D30D	VerLanguageNameW          	.rdata	C:\Windows\SysWOW64\version.VerLanguageNameW          	
00000010	0002D349	VerQueryValueA            	.rdata	C:\Windows\SysWOW64\version.VerQueryValueA            	
00000011	0002D383	VerQueryValueW            	.rdata	C:\Windows\SysWOW64\version.VerQueryValueW            	
00000012	00003586	DllMain                   	.text

**Comment by hamflx** [comment]
@gqf2008 你不能光说不行啊 😂，给点现象啥的，没有执行 version.dll 的 DllMain 吗？或者能不能给一个复现的仓库？

> 最好把DllMain给隐藏掉

这个是特地留的，总不能只构建一个壳子 dll，不执行自己的代码吧，所以这个里面可以放自己的代码。

**Comment by hamflx** [comment]
我直接用仓库里的 `examples/just-call-version` 是可以的：

```plaintext
D:/repos/forward-dll> cargo +stable-i686-pc-windows-msvc build --target i686-pc-windows-msvc
D:/repos/forward-dll> .\target\i686-pc-windows-msvc\debug\just-call-version.exe
==> version.dll loaded
==> just-call-version: GetFileVersionInfoA=true
```

> ==> version.dll loaded

这行表示 version.dll 加载成功。

**Comment by gqf2008** [comment]
@hamflx 关键是我跟踪不到错误（version.dll劫持后是另外一个进程调用了里面的函数），DLL是加载成功的。要不加下微信吧gqingfeng

**Comment by hamflx** [comment]
@gqf2008 哥，你给给复现仓库应该可以吧。。。

**Comment by gqf2008** [comment]
> @gqf2008 你不能光说不行啊 😂，给点现象啥的，没有执行 version.dll 的 DllMain 吗？或者能不能给一个复现的仓库？
> 
> > 最好把DllMain给隐藏掉
> 
> 这个是特地留的，总不能只构建一个壳子 dll，不执行自己的代码吧，所以这个里面可以放自己的代码。

不导出加载器一样会调用DllMain的，不影响dll加载自己的代码

**Comment by hamflx** [comment]
ok，有空我来试一下。
