### ISSUE TITLE
似乎除了version.dll其他dll都无法导出

### ISSUE THREAD

**Issue by gqf2008** [hamflx/forward-dll#3]
@hamflx 尝试了几个常用dll，winmm.dll，winspool.drv都无法正确导出转发

派生洪错误提示如下
proc-macro derive panicked
message: `""` is not a valid identifier

C:\\Windows\\System32\\winmm.dll 编译错误如下
error[E0599]: no method named `init` found for struct `WinmmModule` in the current scope
   --> src\lib.rs:151:27
    |
105 | pub struct WinmmModule;
    | ---------------------- method `init` not found for this struct
...
151 |                 WINMM_LIB.init().unwrap();
    |                           ^^^^ method not found in `WinmmModule`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `init`, perhaps you need to implement it:
            candidate #1: `ForwardModule`

For more information about this error, try `rustc --explain E0599`.
warning: `winspool` (lib) generated 27 warnings
error: could not compile `winspool` (lib) due to 2 previous errors; 27 warnings emitted

C:\\Windows\\System32\\winspool.drv 编译错误如下
error[E0599]: no method named `init` found for struct `WinspoolModule` in the current scope
   --> src\lib.rs:151:30
    |
105 | pub struct WinspoolModule;
    | ------------------------- method `init` not found for this struct
...
151 |                 WINSPOOL_LIB.init().unwrap();
    |                              ^^^^ method not found in `WinspoolModule`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `init`, perhaps you need to implement it:
            candidate #1: `ForwardModule`

For more information about this error, try `rustc --explain E0599`.
warning: `winspool` (lib) generated 27 warnings
error: could not compile `winspool` (lib) due to 2 previous errors; 27 warnings emitted

**Comment by hamflx** [comment]
测试了一下，winmm.dll 有一个符号是仅导出 ordinal，没有名称，目前还没有兼容这种情况，有空我会处理下。

**Comment by hamflx** [comment]
@gqf2008 仅导出 ordinal 的支持了（静态转发），不过我没有测试，也没有发版，可以引用仓库地址：

```toml
[build-dependencies]
forward-dll = { git = "https://github.com/hamflx/forward-dll.git" }
```

**Comment by hamflx** [comment]
动态场景下，单凭宏应该没法实现，因为 rust 本身没有提供设置导出的 ordinal，需要用 build.rs 配合修改链接参数才行，暂时不打算支持了，除非能找到比较好的方法协调两者。

**Comment by hamflx** [comment]
v0.1.16 发布，支持静态的仅导出 ordinal 的转发，动态的暂时没有计划。
