### ISSUE TITLE
你好，虽然这很唐突，希望您能看到！

### ISSUE THREAD

**Issue by Chili1995** [hamflx/forward-dll#4]
我最近遇到vue内存泄漏的问题，看了您的文章“[记一次内存泄漏的排查过程]”很有启发！

但是由于我们系统内容太多了，实在分析找不到引用头绪(┬＿┬)

希望您能看到给予回复，感激不尽

**Comment by hamflx** [comment]
你可以在 <https://github.com/hamflx/content> 处提 `issue`，或在文章下面评论。可以具体说下看看。
